#!/bin/bash

# Check to make sure we have the vars we need to start
if [[ -z "${UWSGIPROBE}" ]]; then
  echo "[NOTICE-UWSGI-DAEMON] ----> Please set the UWSGIPROBE ENV variable and try again"
  exit 1
fi

#Start uwsgi (This assumes we are already in /opt/healthchecks)
echo "[NOTICE-UWSGI-DAEMON] ----> Starting UWSGI"
/usr/local/bin/uwsgi --ini /opt/rtd/uwsgi.ini
echo "[NOTICE-UWSGI-DAEMON] ----> Starting UWSGI Monitoring Service @ 127.0.0.1:1717"

sleep 5 

(echo >/dev/tcp/127.0.0.1/1717) &>/dev/null
if [ $? -eq 0 ]; then
        echo "[NOTICE-UWSGI-DAEMON] ----> UWSGI Started Successfully"
else
        echo "[NOTICE-UWSGI-DAEMON] ----> UWSGI Startup Failed health check @ 127.0.0.1:1717"
        echo "[NOTICE-UWSGI-DAEMON] ----> Startup Failed. Now Exiting"
        break
fi

#Monitor UWSGI to make sure its running
while true; do
 
	(echo >/dev/tcp/127.0.0.1/1717) &>/dev/null
	if [ $? -eq 0 ]; then
		
		sleep $UWSGIPROBE
	else
    		CURRENTTIME=$(date +"%Y-%m-%d %T")
		echo "[NOTICE-UWSGI-DAEMON] ----> UWSGI DID NOT RESPOIND TO STATUS CHECK: ${CURRENTTIME}"
		break
	fi
done 
